### ISSUE TITLE
Support for arrays with 'uniqueItems'

### ISSUE THREAD

**Issue by dvdeurse** [agliznetsov/swagger-tools#1]
There is a property in OpenAPI called ‘uniqueItems’ which you can use to indicate that the items inside an array should be unique (see https://swagger.io/docs/specification/data-models/data-types/#array). If this property is set to true, it would be nice if the Java Set type is used in the generated code, instead of a List type.

**Comment by agliznetsov** [comment]
fixed in #0.5.1
